
macro(clearVars)
    set (APP_CREATES_PLUGINS)
    set (APP_DATA_VERSION)
    set (APP_DATE)
    set (APP_DESCRIPTION)
    set (APP_DOC_CLASS)
    set (APP_FEATURES)
    set (APP_FILE_EXTN)
    set (APP_FILE_FILTERS)
    set (APP_FILE_TYPES)
    set (APP_GENERATE_RECORDSETS)
    set (APP_GENERATE_UI_CLASSES)
    set (APP_HOFFSOFT_LIBS)
    set (APP_MAGIC_BEAN)
    set (APP_NAME)
    set (APP_SHOW_SIZER_INFO_IN_SOURCE)
    set (APP_SUPPLIES_RESOURCES)
    set (APP_TYPE)
    set (APP_USES_PYTHON_GENERATORS)
    set (APP_VENDOR)
    set (APP_VERSION)
    set (APP_VIEW_CLASS)
    set (FIND_PACKAGE_HINTS)
    set (PLUGINS)
endmacro()
