include_guard(GLOBAL)

## HoffSoft build framework delegator (split into global + per-project)
include (cmake/array_enhanced.cmake)
#include (cmake/test_enhanced.cmake)

record(CREATE __regPkgCB "APD_CALLBACKS")
set(__regPkgCB           "${__regPkgCB}"  CACHE  INTERNAL "" FORCE)

array(CREATE __regLibs   "LIBS"           RECORDS)
set(__regLibs            "${__regLibs}"   CACHE  INTERNAL "" FORCE)

record(CREATE __regPlug  "PLUGINS")
set(__regPlug            "${__regPlug}"   CACHE  INTERNAL "" FORCE)

set(__alreadyLocated     ""               CACHE  INTERNAL "" FORCE)

function(registerPackageCallback fn)
    record(CONVERT __regPkgCB)
    if(NOT fn IN_LIST __regPkgCB)
        list(APPEND __regPkgCB ${fn})
        record(CONVERT __regPkgCB)
        msg(${__regPkgCB})
        msg($CACHE{__regPkgCB})
        set(__regPkgCB ${__regPkgCB} CACHE  INTERNAL "" FORCE)
        msg(${__regPkgCB})
        msg($CACHE{__regPkgCB})
        message("${BOLD}Registered${NC} AddPackage callback for ${YELLOW}${fn}${NC}")
    endif ()
    unset(fn)
    msg()
endfunction()

set(LIXNamespace    0)
set(LIXLibName      1)
set(LIXFeatureName  2)
set(LIXIncPath      3)
function(registerLibrary namespace libName nameAsFeature path)
    array(GET __regLibs EQUAL "${namespace}_${libName}" lib)
    if(NOT lib)
        record(CREATE lib "${namespace}_${libName}")
        record(APPEND lib ${namespace} ${libName} ${nameAsFeature} "${path}")
        array(APPEND __regLibs RECORD "${lib}")
    else ()
        record(SET lib 0 ${namespace} ${libName} ${nameAsFeature} "${path}")
        array(SET __regLibs ${namespace}_${libName} "${lib}")
    endif ()
    set (__regLibs "${__regLibs}" CACHE  INTERNAL "" FORCE)
    include("${path}")
    set(fn "init${APP_NAME}")
    if (COMMAND "${fn}") ###############################################################################################
        cmake_language(CALL "${fn}") ###################################################################################
    endif () ###########################################################################################################
    unset(lib)
    unset(fn)
endfunction()
function(getLibraryComponentPart namespace libName LIX value)
    array(GET __regLibs EQUAL ${namespace}_${libName} lib)
    if(NOT lib)
        set(${value} PARENT_SCOPE)
        return()
    endif ()
    record(GET lib ${LIX} v)
    set(${value} ${v} PARENT_SCOPE)
    unset(lib)
    unset(v)
endfunction()

function(registerPlugin pi)
    record(CONVERT __regPlug)
    if(NOT pi IN_LIST __regPlug)
        list(APPEND __regPlug ${pi})
        record(CONVERT __regPlug)
        set(__regPlug "${__regPlug}" CACHE  INTERNAL "" FORCE)
        message("${BOLD}Registered${NC} Plugin for ${YELLOW}${pi}${NC}")
    endif ()
endfunction()

function(savePackageData)
    set(GLOBAL   "${GLOBAL}"   PARENT_SCOPE)
    set(SYSTEM   "${SYSTEM}"   PARENT_SCOPE)
    set(LIBRARY  "${LIBRARY}"  PARENT_SCOPE)
    set(OPTIONAL "${OPTIONAL}" PARENT_SCOPE)
    set(PLUGIN   "${PLUGIN}"   PARENT_SCOPE)
    set(CUSTOM   "${CUSTOM}"   PARENT_SCOPE)
endfunction()

message (NOTICE "\t\tProcessing ${APP_NAME}\n")
#
#set(wguheuIX 0)
#array(LENGTH __regInc wguheuMAX)
#while(wguheuIX LESS wguheuMAX)
#    set(cmcmIX wguheuIX)
#    math(wguheuIX "${wguheuIX} + 1")
#
#    array(GET __regLibs ${wguheuIX} known_lib)
#    if(NOT known_lib)
#        continue()
#    endif ()
#    record(GET known_lib ${LIXIncPath} path)
#    if(path)
#        get_filename_component(path "${path}" ABSOLUTE)
#        include("${path}")
#        set(fn "init${known_lib}")
#        cmake_language(CALL "${fn}")
#
#        list(APPEND REQD_LIBS "${known_lib}")
#    endif ()
#endwhile ()

include(${CMAKE_SOURCE_DIR}/cmake/framework.cmake)
