include_guard(GLOBAL)

## Core build framework delegator (split into global + per-project)
include (${cmake_root}/global.cmake)

function(registerPackageCallback fn dry_run)
    if(NOT COMMAND "${fn}")
        message(FATAL_ERROR "registerPackageCallback(): '${fn}' is not a command")
    endif()
    columnarTextOut("default" "package" "callback" "registered" "for" "handler" "${fn}"
            "[FIELD0:R][FIELD1:L][FIELD2:R][FIELD3:L][FIELD4:R][FIELD5:L]" ${dry_run})
    globalObjAppendUnique("HS_REG_PKG_CALLBACKS" "${fn}")
endfunction()

function(runPackageCallbacks)
    globalObjGet("HS_REG_PKG_CALLBACKS" _cbs)
    foreach(cb IN LISTS _cbs)
        cmake_language(CALL "${cb}" "${ARGV}") # pass-through args if you want
    endforeach()
endfunction()

function(registerLibrary libID namespace libName path)
    string(TOUPPER ${libID} LIBID)
    globalObjAppendUnique("HS_REG_LIB_${LIBID}_NAMESPACE" "${namespace}")
    globalObjAppendUnique("HS_REG_LIB_${LIBID}_NAME"      "${libName}")
    globalObjAppendUnique("HS_REG_LIB_${LIBID}_PATH"      "${path}")
    if(NOT EXISTS "${path}")
        msg(ALWAYS FATAL_ERROR "library registration path \"${RED}${BOLD}${path}${NC}\" does not exist")
    else ()
        msg("Library registration path \"${path}\" ${GREEN}successful${NC}")
    endif ()
    include("${path}")
endfunction()

function(getLibraryInfo libID obj)
    string(TOUPPER ${libID} LIBID)
    globalObjGet("HS_REG_LIB_${LIBID}" local_object)
    set(${obj} ${local_object} PARENT_SCOPE)
endfunction()

function(registerPlugin pi dry_run)
    globalObjAppendUnique(HS_REG_PI_LIST "${pi}")
    columnarTextOut("default" "plugin library" "${pi}" "registered" "" "" ""
            "[FIELD0:R][FIELD1:L][FIELD2:R][FIELD3:L][FIELD4:R][FIELD5:L]" ${dry_run})
endfunction()

math(EXPR _w "${_term_cols} - 2")
string(REPEAT "═" ${_w} _li)
string(REPEAT " " ${_w} _sp)
set(_top "╔${_li}╗")
set(_mid "║${_sp}║")
set(_bot "╚${_li}╝")
set(_tex "Processing ${APP_NAME}")
string(LENGTH "${_tex}" _tel)
math(EXPR _tepl "(${w} - ${tel}) / 2")
math(EXPR _tepr "(${w} - ${tel}) / 2")
math(EXPR _huh "${_tepl} + ${_tepr}")
if (_huh LESS _w)
    math(_tepl "${_tepl} + 1")
endif ()
string(REPEAT " " ${_tepl} _lil)
string(REPEAT " " ${_tepr} _lir)
set(_mex "${_lil}${_tex}${_lir}")

msg()
msg(ALWAYS "${BOLD}${CYAN}${_top}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_mid}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_mid}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_mex}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_mid}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_mid}${NC}")
msg(ALWAYS "${BOLD}${CYAN}${_bot}${NC}")
msg()

include(${cmake_root}/framework.cmake)
