# Add an item to a GLOBAL property list (unique)
function(globalAppendUnique prop value)
    get_property(_list GLOBAL PROPERTY "${prop}")
    if(NOT _list)
        set(_list "")
    endif()

    if(NOT value IN_LIST _list)
        set_property(GLOBAL APPEND PROPERTY "${prop}" "${value}")
    endif()
endfunction()

# Add or update an item to a GLOBAL property list (unique)
function(globalSet prop value)
    get_property(_list GLOBAL PROPERTY "${prop}")
    if(NOT _list)
        set(_list "")
    endif()

    if(NOT value IN_LIST _list)
        set_property(GLOBAL APPEND PROPERTY "${prop}" "${value}")
    else ()
        set_property(GLOBAL PROPERTY "${prop}" "${value}")
    endif()
endfunction()

# Read a GLOBAL property list
function(globalGet prop outVar)
    get_property(_list GLOBAL PROPERTY "${prop}")
    if(NOT _list)
        set(_list "")
    endif()
    set(${outVar} "${_list}" PARENT_SCOPE)
endfunction()
