#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage nike build"
    echo "   or nike stage"
    echo "   or nike install"
    exit 1
fi

if [ "${1}" == 'build' ]; then
    target=$(basename $(pwd))
elif [ "${1}" == 'stage' ]; then
    target="install"
    mkdir -p /tmp/stage 
elif [ "${1}" == 'install' ]; then
    target='install'
else    
    echo "Usage nike build"
    echo "   or nike stage"
    echo "   or nike install"
    exit 1
fi

for l in gtk3 Qt6; do
    if [ -e "build/clang/${l}/debug/shared" ]
    then
        if [ ${1} == 'build' ]
        then 
            echo cmake --build build/clang/${l}/debug/shared --target ${target}
            cmake --build build/clang/${l}/debug/shared --target ${target}
        fi
        if [ ${1} == 'stage'   ]
        then 
            echo DESTDIR=/tmp/stage cmake --build build/clang/${l}/debug/shared --target ${target}
            DESTDIR=/tmp/stage cmake --build build/clang/${l}/debug/shared --target ${target}
        fi
        if [ ${1} == 'install' ]
        then 
            echo sudo cmake --build build/clang/${l}/debug/shared --target ${target}
            sudo cmake --build build/clang/${l}/debug/shared --target ${target}
        fi
    fi
done

