#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage nike build"
    echo "   or nike stage"
    echo "   or nike install"
    exit 1
fi

if [ "${1}" == 'build' ]; then
    target=$(basename $(pwd))
    noun=''
elif [ "${1}" == 'stage' ]; then
    target="install"
    noun='DESTDIR=/tmp/stage'
elif [ "${1}" == 'install' ]; then
    target='install'
    noun='sudo'
else    
    echo "Usage nike build"
    echo "   or nike stage"
    echo "   or nike install"
    exit 1
fi

for l in gtk3 Qt6; do 
    echo ${noun} cmake --build build/clang/${l}/debug/shared --target ${target}
    ${noun} cmake --build build/clang/${l}/debug/shared --target ${target}
done

