#!/bin/bash

ok=0
if [[ "$1" == "data" ]] || [[ "$1" == "all" ]]
then
    rm -f ~/Documents/*.mcdb
    rm -rf ~/.MyCare
    rm -rf ~/.HoffSoft/MyCare
    rm -rf ~/.cache/HoffSoft
    rm -rf ~/.cache/MyCare
    rm -rf ~/Library/Caches/HoffSoft/MyCare

    echo 'data gone'
    ok=1
fi

if [[ "$1" == "generated" ]] || [[ "$1" == "all" ]]
then
    rm -rf src/generated

    echo 'generated gone'
    ok=1
fi

if [[ "$1" == "build" ]] || [[ "$1" == "all" ]]
then
    rm -rf build
    rm -rf external
    rm -rf out
    echo 'build gone'
    ok=1
fi

if [[ "$1" == "everything!" ]]
then
    project=$(basename $(pwd))

    echo -n "Completely remove ${project}? <Enter> for yes, ^C if not > "
    read    
    cd .. && rm -rf "${project}" && git clone --recurse https://$GITOKEN@github.com/ga2k/${project}.git && cd "${project}" && ./cmake/setup
    
    ok=1
fi

if (( ok == 0 ))
then
    echo "Usage: nuke data | generated | build | all | everything!"
fi

