#!/bin/bash

# Run the Python script to update CMakePresets.json
python3 CMakeFiles/filter-presets.py CMakeFiles/templates/CMakePresets.in CMakePresets.json
(( $? == 0 )) && echo "CMake presets have been set UP!"
