function(soci_postDeclare librariesList didFetch)
    message("soci requires sqlite3, so lets get it.")
    if (WIN32)
        find_package(unofficial-sqlite3 CONFIG REQUIRED)
        list(APPEND librariesList unofficial::sqlite3::sqlite3)
    else ()
        find_library(sqllib sqlite3)
        if (${sqllib} STREQUAL "sqlite3_NOTFOUND")
            message(FATAL_ERROR "Required library SQLite3 not found")
        endif ()
#        list(APPEND librariesList ${sqllib})
    endif ()
    set(_LibrariesList ${librariesList} PARENT_SCOPE)
endfunction()

soci_postDeclare("${_LibrariesList}" "${this_fetch}")
set(_LibrariesList ${_LibrariesList} PARENT_SCOPE)
set(HANDLED ON)
