function (wxWidgets_preDownload pkgname url tag srcDir)
    include(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/helpers.cmake)
    wxWidgets_set_build_options()
    set(HANDLED OFF PARENT_SCOPE)
endfunction()
